project:
  type: website

website:
  title: "Environmental Data Science Summit"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: yeti
    css: styles.css
    toc: false

editor: visual

