project:
  type: website
  output-dir: docs

website:
  title: "Environmental Data Science Summit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog_listing.qmd
        text: EDSS Blog

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

