project:
  type: website
  execute-dir: project
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Environmental Data Science Summit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog_listing.qmd
        text: EDSS Blog
    right: 
      - icon: github
        href: https://github.com/EDS-Summit/eds-summit.github.io

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

